<a href="https://colab.research.google.com/github/iu02-0225-1098-prog/IPL-DATASET/blob/main/job_salary_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded =files.upload()

Saving job_salary_prediction_dataset.csv to job_salary_prediction_dataset.csv

In [ ]:
#import some librarries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
datasummiya = pd.read_csv('job_salary_prediction_dataset.csv')

Exploratory Data Analysis

In [ ]:
datasummiya.shape

(250000, 10)

In [ ]:
datasummiya.head(10)

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069
5,AI Engineer,0,High School,4,Education,Enterprise,USA,No,2,180351
6,Backend Developer,6,High School,16,Manufacturing,Enterprise,Canada,No,3,165375
7,Machine Learning Engineer,4,Bachelor,18,Healthcare,Enterprise,Canada,Hybrid,5,202463
8,AI Engineer,5,Diploma,14,Telecom,Enterprise,Singapore,Yes,0,171834
9,Frontend Developer,18,PhD,2,Retail,Enterprise,India,Hybrid,5,128377

In [ ]:
datasummiya.describe()

       experience_years   skills_count  certifications         salary
count     250000.000000  250000.000000   250000.000000  250000.000000
mean          10.005408       9.997812        2.491928  145718.080524
std            6.060602       5.479288        1.706475   37407.952729
min            0.000000       1.000000        0.000000   31867.000000
25%            5.000000       5.000000        1.000000  119358.000000
50%           10.000000      10.000000        2.000000  143453.000000
75%           15.000000      15.000000        4.000000  169492.000000
max           20.000000      19.000000        5.000000  333046.000000

In [ ]:
datasummiya.tail(6)

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
249994,Business Analyst,13,Diploma,17,Finance,Large,USA,Yes,3,171896
249995,Software Engineer,17,PhD,2,Telecom,Enterprise,India,No,1,127791
249996,Frontend Developer,20,PhD,7,Telecom,Startup,Remote,No,2,154593
249997,Business Analyst,1,Bachelor,12,Retail,Enterprise,India,Yes,0,75988
249998,Data Scientist,0,High School,2,Consulting,Small,Sweden,Hybrid,5,90467
249999,Data Analyst,16,Diploma,2,Technology,Medium,UK,No,5,133084

In [ ]:
datasummiya.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  object
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  object
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  object
 5   company_size      250000 non-null  object
 6   location          250000 non-null  object
 7   remote_work       250000 non-null  object
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), object(6)
memory usage: 19.1+ MB

In [ ]:
datasummiya.iloc[:, :-1]

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0
...,...,...,...,...,...,...,...,...,...
249995,Software Engineer,17,PhD,2,Telecom,Enterprise,India,No,1
249996,Frontend Developer,20,PhD,7,Telecom,Startup,Remote,No,2
249997,Business Analyst,1,Bachelor,12,Retail,Enterprise,India,Yes,0
249998,Data Scientist,0,High School,2,Consulting,Small,Sweden,Hybrid,5
249999,Data Analyst,16,Diploma,2,Technology,Medium,UK,No,5

In [ ]:
datasummiya.isnull().sum()

job_title           0
experience_years    0
education_level     0
skills_count        0
industry            0
company_size        0
location            0
remote_work         0
certifications      0
salary              0
dtype: int64

Data Preprocessing

In [ ]:
datasummiya['location'].value_counts()

location
Australia      25258
Canada         25165
Sweden         25100
Remote         25065
Singapore      25035
USA            24931
UK             24927
India          24895
Netherlands    24861
Germany        24763
Name: count, dtype: int64

Numerical

In [ ]:
datasummiya = pd.get_dummies(datasummiya, drop_first=True)

Features & Target

In [ ]:
x = datasummiya.drop('salary', axis=1)
y = datasummiya['salary']

Data Visualization

In [ ]:
import matplotlib.pyplot as plt